version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:80"
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: unless-stopped 